### ISSUE TITLE
图像恢复

### ISSUE THREAD

**Issue by JunliShi** [HuaYuuu/PDI2A-CVPR2022#1]
同学你好，恭喜你们组中了CVPR，我辈楷模！！我最近在研究沙尘图像恢复，和你们现在中的这篇文章方向接近，所以冒昧留言，进行讨论。我有如下几个问题：
1.文章中出现的合成图像，合成的颜色设置了固定值，是收集了部分真实图像确定的A值吗？是按照何博士DCP方法确定出来的A值吗？？

2.观察到文中出现的在真实有色雾上恢复的情况，远处天空部分有一些偏脏。想问一下在测试的535张真实图像中是在颜色偏移严重的图像出现的通病吗？（无意冒犯吖）

3.对multi-head编码器产生的A与真实无色的雾图像产生的A，做逼近？是这个意思吗？

**Comment by HuaYuuu** [comment]
您好，感谢对我们工作的关注。我已经在邮件中一一回复了您的疑问，后续有其他问题可以进一步沟通和交流。

**Comment by hello-trouble** [comment]
> 同学你好，恭喜你们组中了CVPR，我辈楷模！！我最近在研究沙尘图像恢复，和你们现在中的这篇文章方向接近，所以冒昧留言，进行讨论。我有如下几个问题： 1.文章中出现的合成图像，合成的颜色设置了固定值，是收集了部分真实图像确定的A值吗？是按照何博士DCP方法确定出来的A值吗？？
> 
> 2.观察到文中出现的在真实有色雾上恢复的情况，远处天空部分有一些偏脏。想问一下在测试的535张真实图像中是在颜色偏移严重的图像出现的通病吗？（无意冒犯吖）
> 
> 3.对multi-head编码器产生的A与真实无色的雾图像产生的A，做逼近？是这个意思吗？
您好，请教一下沙尘图像恢复有没有综述论文呢？

**Comment by hello-trouble** [comment]
> 同学你好，恭喜你们组中了CVPR，我辈楷模！！我最近在研究沙尘图像恢复，和你们现在中的这篇文章方向接近，所以冒昧留言，进行讨论。我有如下几个问题： 1.文章中出现的合成图像，合成的颜色设置了固定值，是收集了部分真实图像确定的A值吗？是按照何博士DCP方法确定出来的A值吗？？
> 
> 2.观察到文中出现的在真实有色雾上恢复的情况，远处天空部分有一些偏脏。想问一下在测试的535张真实图像中是在颜色偏移严重的图像出现的通病吗？（无意冒犯吖）
> 
> 3.对multi-head编码器产生的A与真实无色的雾图像产生的A，做逼近？是这个意思吗？



您好，请教一下，沙尘图像恢复有没有比较新的综述呢？想学习了解一下。

**Comment by HuaYuuu** [comment]
> 

沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。

**Comment by hello-trouble** [comment]
> > 
> 
> 沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。



> > 
> 
> 沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。

谢谢指点，我去找一下水下图像复原相关的论文学习学习。请教一下，咱们合成有色雾的代码能否帮我发一下呢？2095886128@qq.com

**Comment by hello-trouble** [comment]
> > 
> 
> 沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。

谢谢您的指点，我去找找对应的文章学习学习。另外请教一下，沙尘图像或者有色雾去除有开源代码的吗？我只找到了一篇2016的文章代码

**Comment by hello-trouble** [comment]
> > 
> 
> 沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。

您好，谢谢指点。请教一下沙尘图像复原有比较新且开源代码的论文吗？

**Comment by hello-trouble** [comment]
> > 
> 
> 沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。

您好，谢谢您的指点。 我去找找相应的论文学习学习。另外，再请教一下，沙尘图像复原有没有近两年开源代码的论文呢？

**Comment by JunliShi** [comment]
你好，之前我以为邮件是延迟发送的，以为是文章的李玮学长答复的，所以也没有具体看邮件的内容。现在才回复你的信息，真的很不好意思。
第一个问题：沙尘图像的综述。没得综述，都是自己搞的。我个人感觉主要原因是大部分依据大气散射模型，也就算是传统方法吧，基本上没有使用端到端的深度学习方法。
第二个问题：合成有色雾。这个是我们组里的工作，主要是根据真实沙尘图像空间分布规律来合成的沙尘图像。







------------------ 原始邮件 ------------------
发件人: Trouble_in ***@***.***&gt;
发送时间: 2022年8月4日 08:48
收件人: HuaYuuu/PDI2A-CVPR2022 ***@***.***&gt;
抄送: JunliShi ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [HuaYuuu/PDI2A-CVPR2022] 图像恢复 (Issue #1)





    
沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。
  
谢谢您的指点，我去找找对应的文章学习学习。另外请教一下，沙尘图像或者有色雾去除有开源代码的吗？我只找到了一篇2016的文章代码

**Comment by JunliShi** [comment]
第三个问题，去除真实沙尘图像的代码。我把方法分为两种，一种是传统方法的（基于大气光散射模型的）一种是深度学习的。
传统方法里边应该有六七种吧，从14年，厦门大学Fu的那篇文献，方法名称是MMSP，具体文章名字我给忘了（不好意思啊）他开始就有了。


基于深度学习的方法，目前我知道的，中科大有一组也是合成沙尘图像，直接用Pix2Pix跑的去沙，没有自己针对提出去沙网络。还有一组，西安理工大学，石争浩老师那组做这个方向好几年了，从他近两年文章发现，他们组开始合成数据集，用深度学习方法。


具体有什么问题可以微信联系我，这样我可以比较快看到。我微信号：Nov14_Jun





------------------ 原始邮件 ------------------
发件人: Trouble_in ***@***.***&gt;
发送时间: 2022年8月4日 08:48
收件人: HuaYuuu/PDI2A-CVPR2022 ***@***.***&gt;
抄送: JunliShi ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [HuaYuuu/PDI2A-CVPR2022] 图像恢复 (Issue #1)





    
沙尘图像复原目前我没有看到专门的综述文章，不过目前来说沙尘图像复原、水下图像复原这几个小领域都有共同之处。你可以尝试找找水下图像复原、还有2021 CVPR Varicolored Image Dehazing的相关工作来看一下。
  
谢谢您的指点，我去找找对应的文章学习学习。另外请教一下，沙尘图像或者有色雾去除有开源代码的吗？我只找到了一篇2016的文章代码

**Comment by zhenyuan1234** [comment]
> 合成沙尘图像

你好，请问现在有没有真实世界的风沙数据集，谢谢！

**Comment by JunliShi** [comment]
我当时用的真实世界沙尘图像来源主要分为以下三个部分：一、继承了学长学姐的一部分；二、网上搜集了一部分：三、我们组里去新疆的南疆等地在春季容易出现沙尘暴天气的地区采集了一部分。这个真实世界沙尘图像暂时没见哪个组开源出来给大家研究用，感觉好像都是自己组里搞的。 ---- 回复的原邮件 ***@***.***>发送日期2024年03月02日 20:09 ***@***.***> ***@***.***>***@***.***>主题Re: [HuaYuuu/PDI2A-CVPR2022] 图像恢复 (Issue #1)

合成沙尘图像

你好，请问现在有没有真实世界的风沙数据集，谢谢！

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/HuaYuuu/PDI2A-CVPR2022/issues/1#issuecomment-1974779410",
"url": "https://github.com/HuaYuuu/PDI2A-CVPR2022/issues/1#issuecomment-1974779410",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JunliShi** [comment]
我当时用的真实世界沙尘图像来源主要分为以下三个部分：一、继承了学长学姐的一部分；二、网上搜集了一部分：三、我们组里去新疆的南疆等地在春季容易出现沙尘暴天气的地区采集了一部分。这个真实世界沙尘图像暂时没见哪个组开源出来给大家研究用，感觉好像都是自己组里搞的。---- 回复的原邮件 ***@***.***>发送日期2024年03月02日 20:09 ***@***.***> ***@***.***>***@***.***>主题Re: [HuaYuuu/PDI2A-CVPR2022] 图像恢复 (Issue #1)

合成沙尘图像

你好，请问现在有没有真实世界的风沙数据集，谢谢！

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/HuaYuuu/PDI2A-CVPR2022/issues/1#issuecomment-1974779410",
"url": "https://github.com/HuaYuuu/PDI2A-CVPR2022/issues/1#issuecomment-1974779410",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
