### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by zlou** [HuaYuuu/PDI2A-CVPR2022#3]
Hi, 
Thanks for the interesting work. I am wondering when the code and model will be open sourced?

**Comment by HuaYuuu** [comment]
Hi,
sorry for the delay of the code release. Unfortunately, I'm struggling to finish the work on the foundation from my mentor. Thus I have little time to reorganize the code for release. I will finish the code reorganization as soon as possible after the foundation work and release it.
Thanks for the patience and understanding!
